In [2]:
import py_dss_interface
from py_dss_toolkit import dss_tools

dss = py_dss_interface.DSS()

dss_file = r"C:\Dados_teste\OpenDSS\CBA\Alim_Meia_Ponte_5_REDUZIDO\Master_PyDSS_Interface.dss"
#dss_file = r"C:\Users\IVAN SANTOS\Documents\OpenDSS\Alim_Meia_Ponte_5_REDUZIDO\Master_PyDSS_Interface.dss"

dss_tools.update_dss(dss)

dss.text(f"compile [{dss_file}]")

#dss.text("Redirect 'PV_System_60_MeiaPonte.dss'")

dss.text(f"buscoords BusCoords.csv")

dss.text("set mode=daily")
dss.text("set stepsize=1h")
dss.text("set number=24")
dss.solution.solve()

df_energymeter = dss_tools.results.energymeters

display(df_energymeter)

,name,kwh,kvarh,max kw,max kva,zone kwh,zone kvarh,zone max kw,zone max kva,overload kwh normal,...,aux19,aux24,aux29,13.8 kv load energy,aux5,aux10,aux15,aux20,aux25,aux30
0,busa4-_2021126072_segmmt_53951427,124421.081474,63076.686747,7065.687191,8103.461649,118141.936302,49529.463882,6612.56024,7223.772169,107.853497,...,0.0,0.0,0.0,118141.936302,0.0,0.0,0.0,0.0,0.0,0.0

Cargas

In [3]:
loads_df = dss_tools.model.loads_df
loads_df

,name,phases,bus1,kv,kw,pf,model,yearly,daily,duty,...,zipv,%seriesrl,relweight,vlowpu,puxharm,xrharm,spectrum,basefreq,enabled,like
0,mt_10009727955_m1,3,88185385002086.1.2.3.4,13.8,5.46925728729341,0.9021,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
1,mt_10009727955_m2,3,88185385002086.1.2.3.4,13.8,5.46925728729341,0.9021,3,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
2,mt_10014416466_m1,3,89458365002086.1.2.3.4,13.8,2.65068009244008,0.9021,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
3,mt_10014416466_m2,3,89458365002086.1.2.3.4,13.8,2.65068009244008,0.9021,3,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
4,mt_10015559007_m1,3,89813615002086.1.2.3.4,13.8,2.32027223167495,0.9021,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,m1_trf_5333902a,3,85167275333902.1.2.3.4,0.38,26.2254249405443,0.9076,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
302,m1_trf_5740255a,3,82056945740255.1.2.3.4,0.38,14.5905864350407,0.9101,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
303,m1_trf_5740270a,3,96033635740270.1.2.3.4,0.38,12.2445576749837,0.9097,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
304,m1_trf_5744153a,3,96264655744153.1.2.3.4,0.38,16.4320475658323,0.9072,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,
305,m1_trf_5444435a,3,81481405444435.1.2.3.4,0.38,11.0902798793934,0.9097,2,,CURVA,,...,,50,1,0.5,0,6,defaultload,60,true,

Mapas

In [4]:
dss_tools.results.set_violation_voltage_ln_limits( v_min_pu=0.92, v_max_pu=1.05)
dss_tools.interactive_view.circuit_geoplot("voltage violations", show=True, title="Mapa - Violações de Tensão")

In [8]:
import os
print(os.getcwd())
dss_tools.interactive_view.circuit_geoplot(
    parameter="active power", 
    show=True, 
    save_file_path="circuito.html",
    width_3ph=1,
    width_2ph=1,
    width_1ph=1)

C:\Dados_teste\OpenDSS\CBA\Alim_Meia_Ponte_5_REDUZIDO